#!/bin/csh
# http://www.gnu.org/software/libc/download.html
set d=`mktemp -d`
cd $d
git clone git://sourceware.org/git/glibc.git
cd glibc
mkdir build
cd build
../configure --prefix=/tmp
make
./testrun.sh $HOME/svn/mpcheck/mpcheck-double --RNDZ=0 --RNDD=0 --RNDU=0
cd /tmp
/bin/rm -fr $d
