#!/bin/csh
# http://www.gnu.org/software/libc/download.html
set d=`mktemp -d`
cd $d
git clone git://sourceware.org/git/glibc.git
cd glibc
mkdir build
cd build
../configure --prefix=/tmp
make -j4 >& /dev/null
ln -s /usr/lib/x86_64-linux-gnu/libgmp.so.10 .
ln -s /usr/lib/x86_64-linux-gnu/libmpfr.so.6 .
ln -s /usr/lib/x86_64-linux-gnu/libquadmath.so.0 .
./testrun.sh $HOME/svn/mpcheck/mpcheck-float --num=$1 --verbose=3
echo ""
./testrun.sh $HOME/svn/mpcheck/mpcheck-double --num=$1 --verbose=3
echo ""
./testrun.sh $HOME/svn/mpcheck/mpcheck-longdouble --num=$1 --verbose=3
cd /tmp
/bin/rm -fr $d
