#!/bin/csh
# http://www.gnu.org/software/libc/download.html
set d=`mktemp -d`
cd $d
git clone git://sourceware.org/git/glibc.git
cd glibc
mkdir build
cd build
../configure --prefix=/tmp
make >& /dev/null
./testrun.sh $HOME/svn/mpcheck/mpcheck-float --num=1000000 --verbose=3
echo ""
./testrun.sh $HOME/svn/mpcheck/mpcheck-double --num=1000000 --verbose=3
echo ""
./testrun.sh $HOME/svn/mpcheck/mpcheck-longdouble --num=1000000 --verbose=3
cd /tmp
/bin/rm -fr $d
